apiVersion: apps/v1
kind: Deployment
metadata:
  name: aina-app-deployment
  labels:
    app: aina-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aina-app
  template:
    metadata:
      labels:
        app: aina-app
    spec:
      containers:
      - name: aina-app-container
        image: nantenaina11/aina-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000  
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: aina-app-service
spec:
  type: NodePort
  selector:
    app: aina-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000  
    nodePort: 30080