apiVersion: apps/v1
kind: Deployment
metadata:
  name: ONG-app
  labels:
    app: ONG-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ONG-app
  template:
    metadata:
      labels:
        app: ONG-app
    spec:
      containers:
      - name: ONG-app-container
        image: nantenaina11/ONG-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: ONG-app-service
spec:
  type: NodePort
  selector:
    app: ONG-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080